# ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install backend dependencies and run tests
        working-directory: ./backend
        run: |
          npm install
          npm test

      - name: Install frontend dependencies and check build
        working-directory: ./frontend
        run: |
          npm install
          npm run build
